In [29]:
import numpy as np

In [30]:
a = [ i for i in range(10)]

In [31]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
b = np.array(a)

In [33]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
type(b)

numpy.ndarray

In [35]:
b.size

10

In [36]:
b.shape

(10,)

In [37]:
b[0][0]

IndexError: invalid index to scalar variable.

In [38]:
b.shape

(10,)

In [39]:
a = np.array([0,1,2,3,4])

In [40]:
b = np.array([5,6,7,8,9])

In [41]:
c = a+b

In [42]:
c

array([ 5,  7,  9, 11, 13])

x1 = [0,1,2,3,4]
x2 = [5,6,7,8,9]

In [43]:
x1+x2

NameError: name 'x1' is not defined

In [44]:
x1=[0,1,2,3,4]
x2=[5,6,7,8,9]

In [45]:
x1+x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
import numpy as np

In [47]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])

In [48]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [49]:
a_mean = a.mean(axis=0)

In [50]:
a_mean

array([2. , 8.4])

In [51]:
a_centered = a-a_mean

In [52]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [53]:
a_centeres_sp = np.array([[-1,0,1,1,-1],[-2.4,-0.4,2.6,1.6,-1.4]])

In [54]:
a_centeres_sp

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [55]:
import pandas as pd

In [56]:
authors = pd.DataFrame({'author_id':[1,2,3], 'author_name':['Туренев','Чехов','Островский']},
                      columns = ['author_id','author_name'])

In [57]:
authors

author_id author_name
0          1     Туренев
1          2       Чехов
2          3  Островский

In [58]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
                                   'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]},
                   columns = ['author_id','book_title','price'])

In [59]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [60]:
authors_price = pd.merge(authors,book,on = 'author_id',how = 'inner')

In [61]:
authors_price

author_id author_name            book_title  price
0          1     Туренев           Отцы и дети    450
1          1     Туренев                 Рудин    300
2          1     Туренев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [62]:
top5 = authors_price['price'].max()

In [63]:
top5

500

In [64]:
top5 = authors_price.nlargest(5, 'price')

In [65]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1     Туренев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1     Туренев  Дворянское гнездо    350

In [66]:
authors_stat = authors_price['author_name'].value_counts()

In [67]:
authors_stat

Туренев       3
Чехов         2
Островский    2
Name: author_name, dtype: int64

In [68]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

In [69]:
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Туренев           300       450  366.666667
Чехов             450       500  475.000000